src/Entity/Agent.php
<?php

namespace App\Entity;

use App\Repository\AgentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AgentRepository::class)]
class Agent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $last_name = null;

    #[ORM\Column(length: 50)]
    private ?string $first_name = null;

    #[ORM\Column(length: 50)]
    private ?string $identification_code = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birthday = null;

    #[ORM\Column(length: 50)]
    private ?string $nationality = null;

    #[ORM\ManyToOne(inversedBy: 'agents')]
    private ?Mission $mission = null;

    #[ORM\ManyToOne(inversedBy: 'agents')]
    private ?Skill $skill = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getIdentificationCode(): ?string
    {
        return $this->identification_code;
    }

    public function setIdentificationCode(string $identification_code): self
    {
        $this->identification_code = $identification_code;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getMission(): ?Mission
    {
        return $this->mission;
    }

    public function setMission(?Mission $mission): self
    {
        $this->mission = $mission;

        return $this;
    }

    public function getSkill(): ?Skill
    {
        return $this->skill;
    }

    public function setSkill(?Skill $skill): self
    {
        $this->skill = $skill;

        return $this;
    }
    //on va passer l'objet en string
    public function __toString(): string
    {
        return (string) $this->identification_code;
    }
}

src/Form/AgentType.php
<?php

namespace App\Form;

use App\Entity\Agent;
use App\Entity\Skill;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class AgentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('last_name')
            ->add('first_name')
            ->add('identification_code')
            ->add('birthday', DateType::class, [
                'widget' => 'choice',
                'format' => 'y-M-d',
                'years' => range(date("Y") - 90, date("Y") - 18)
            ])
            ->add('nationality', ChoiceType::class, [
                'choices' => [
                    'Belgium' => 'Belgium',
                    'Brazil' => 'Brazil',
                    'China' => 'China',
                    'Congo' => 'Congo',
                    'France' => 'France',
                    'Japan' => 'Japan',
                    'UK' => 'UK',
                    'USA' => 'USA',
                    'Russia' => 'Russia',
                    'Swiss' => 'Swiss',
                ]
            ])
            ->add('skill', EntityType::class, [
                'choice_label' => 'name',
                'class' => skill::class,
                'multiple' => false,
                'expanded' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Agent::class,
        ]);
    }
}

src/Controller/AgentController.php
<?php

namespace App\Controller;

use App\Entity\Agent;
use App\Form\AgentType;
use App\Repository\AgentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('admin/agents')]
class AgentController extends AbstractController
{
    #[Route('/', name: 'app_agent_index', methods: ['GET'])]
    public function index(AgentRepository $agentRepository): Response
    {
        return $this->render('agent/index.html.twig', [
            'agents' => $agentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_agent_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AgentRepository $agentRepository): Response
    {
        $agent = new Agent();
        $form = $this->createForm(AgentType::class, $agent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $agentRepository->add($agent, true);

            return $this->redirectToRoute('app_agent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agent/new.html.twig', [
            'agent' => $agent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_agent_show', methods: ['GET'])]
    public function show(Agent $agent): Response
    {
        return $this->render('agent/show.html.twig', [
            'agent' => $agent,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_agent_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Agent $agent, AgentRepository $agentRepository): Response
    {
        $form = $this->createForm(AgentType::class, $agent);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $agentRepository->add($agent, true);

            return $this->redirectToRoute('app_agent_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('agent/edit.html.twig', [
            'agent' => $agent,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_agent_delete', methods: ['POST'])]
    public function delete(Request $request, Agent $agent, AgentRepository $agentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agent->getId(), $request->request->get('_token'))) {
            $agentRepository->remove($agent, true);
        }

        return $this->redirectToRoute('app_agent_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/agent/_delete_form.html.twig
<form method="post" action="{{ path('app_agent_delete', {'id': agent.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agent.id) }}">
    <button class="btn">Delete</button>
</form>

templates/agent/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/agent/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Agent{% endblock %}

{% block body %}
    <h1>Edit Agent</h1>

    {{ include('agent/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_agent_index') }}">back to list</a>

    {{ include('agent/_delete_form.html.twig') }}
{% endblock %}

templates/agent/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agents index{% endblock %}

{% block body %}
    <h1>Agents index</h1>

    <table class="table table-striped table-hover table-responsive text-center">
        <thead>
            <tr>
                <th>Id</th>
                <th>Last_name</th>
                <th>First_name</th>
                <th>Identification_code</th>
                <th>Birthday</th>
                <th>Nationality</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for agent in agents %}
            <tr>
                <td>{{ agent.id }}</td>
                <td>{{ agent.lastName }}</td>
                <td>{{ agent.firstName }}</td>
                <td>{{ agent.identificationCode }}</td>
                <td>{{ agent.birthday ? agent.birthday|date('Y-m-d') : '' }}</td>
                <td>{{ agent.nationality }}</td>
                <td>
                    <a href="{{ path('app_agent_show', {'id': agent.id}) }}">show</a>
                    <a href="{{ path('app_agent_edit', {'id': agent.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_agent_new') }}">Create new agent</a>
{% endblock %}

templates/agent/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Agent{% endblock %}

{% block body %}
    <h1>Create new Agent</h1>

    {{ include('agent/_form.html.twig') }}

    <a href="{{ path('app_agent_index') }}">back to list</a>
{% endblock %}

templates/agent/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agent{% endblock %}

{% block body %}
    <h1>Agent</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ agent.id }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ agent.lastName }}</td>
            </tr>
            <tr>
                <th>First_name</th>
                <td>{{ agent.firstName }}</td>
            </tr>
            <tr>
                <th>Identification_code</th>
                <td>{{ agent.identificationCode }}</td>
            </tr>
            <tr>
                <th>Birthday</th>
                <td>{{ agent.birthday ? agent.birthday|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nationality</th>
                <td>{{ agent.nationality }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_agent_index') }}">back to list</a>

    <a href="{{ path('app_agent_edit', {'id': agent.id}) }}">edit</a>

    {{ include('agent/_delete_form.html.twig') }}
{% endblock %}