src/Entity/Mission.php
<?php

namespace App\Entity;

use App\Repository\MissionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MissionRepository::class)]
class Mission
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $mission_code_name = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 50)]
    private ?string $mission_type = null;

    #[ORM\Column(length: 40)]
    private ?string $mission_status = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\ManyToOne(inversedBy: 'missions')]
    private ?Skill $skill = null;

    #[ORM\ManyToOne(inversedBy: 'missions')]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'mission', targetEntity: Agent::class)]
    private Collection $agents;

    #[ORM\OneToMany(mappedBy: 'mission', targetEntity: Target::class)]
    private Collection $targets;

    #[ORM\OneToMany(mappedBy: 'mission', targetEntity: Contact::class)]
    private Collection $contacts;

    #[ORM\OneToMany(mappedBy: 'mission', targetEntity: Hideout::class)]
    private Collection $hideouts;

    #[ORM\Column(length: 50)]
    private ?string $country = null;

    public function __construct()
    {
        $this->agents = new ArrayCollection();
        $this->targets = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->hideouts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMissionCodeName(): ?string
    {
        return $this->mission_code_name;
    }

    public function setMissionCodeName(string $mission_code_name): self
    {
        $this->mission_code_name = $mission_code_name;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getMissionType(): ?string
    {
        return $this->mission_type;
    }

    public function setMissionType(string $mission_type): self
    {
        $this->mission_type = $mission_type;

        return $this;
    }

    public function getMissionStatus(): ?string
    {
        return $this->mission_status;
    }

    public function setMissionStatus(string $mission_status): self
    {
        $this->mission_status = $mission_status;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getSkill(): ?Skill
    {
        return $this->skill;
    }

    public function setSkill(?Skill $skill): self
    {
        $this->skill = $skill;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Agent>
     */
    public function getAgents(): Collection
    {
        return $this->agents;
    }

    public function addAgent(Agent $agent): self
    {
        if (!$this->agents->contains($agent)) {
            $this->agents[] = $agent;
            $agent->setMission($this);
        }

        return $this;
    }

    public function removeAgent(Agent $agent): self
    {
        if ($this->agents->removeElement($agent)) {
            // set the owning side to null (unless already changed)
            if ($agent->getMission() === $this) {
                $agent->setMission(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Target>
     */
    public function getTargets(): Collection
    {
        return $this->targets;
    }

    public function addTarget(Target $target): self
    {
        if (!$this->targets->contains($target)) {
            $this->targets[] = $target;
            $target->setMission($this);
        }

        return $this;
    }

    public function removeTarget(Target $target): self
    {
        if ($this->targets->removeElement($target)) {
            // set the owning side to null (unless already changed)
            if ($target->getMission() === $this) {
                $target->setMission(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setMission($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getMission() === $this) {
                $contact->setMission(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Hideout>
     */
    public function getHideouts(): Collection
    {
        return $this->hideouts;
    }

    public function addHideout(Hideout $hideout): self
    {
        if (!$this->hideouts->contains($hideout)) {
            $this->hideouts[] = $hideout;
            $hideout->setMission($this);
        }

        return $this;
    }

    public function removeHideout(Hideout $hideout): self
    {
        if ($this->hideouts->removeElement($hideout)) {
            // set the owning side to null (unless already changed)
            if ($hideout->getMission() === $this) {
                $hideout->setMission(null);
            }
        }

        return $this;
    }
    //on va passer l'objet en string
    public function __toString(): string
    {
        return (string) $this->mission_code_name;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

}

src/Form/MissionType.php
<?php

namespace App\Form;

use App\Entity\Mission;
use App\Entity\Skill;
use App\Entity\Agent;
use App\Entity\Contact;
use App\Entity\Hideout;
use App\Entity\Target;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


class MissionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('mission_code_name')
            ->add('title')
            ->add('description')
            ->add('mission_type', ChoiceType::class, [
                'choices' => [
                    'Surveillance' => 'Surveillance',
                    'Murder' => 'Murder',
                    'Infiltration' => 'Infiltration',
                    'Sabotage' => 'Sabotage',
                ]
            ])
            ->add('mission_status', ChoiceType::class, [
                'choices' => [
                    'In preparation' => 'In preparation',
                    'Current' => 'Current',
                    'Ended' => 'Ended',
                    'Failure' => 'Failure',
                ]
            ])
            ->add('start_date')
            ->add('end_date')
            ->add('country', ChoiceType::class, [
                'choices' => [
                    'Belgium' => 'Belgium',
                    'Brazil' => 'Brazil',
                    'China' => 'China',
                    'Congo' => 'Congo',
                    'France' => 'France',
                    'Japan' => 'Japan',
                    'UK' => 'UK',
                    'USA' => 'USA',
                    'Russia' => 'Russia',
                    'Swiss' => 'Swiss',
                ]
            ])
            ->add('agents', EntityType::class, [
                'choice_label' => 'identification_code',
                'class' => agent::class,
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('skill', EntityType::class, [
                'choice_label' => 'name',
                'class' => skill::class,
                'multiple' => false,
                'expanded' => false,
            ])
            ->add('targets')
            ->add('targets', EntityType::class, [
                'choice_label' => 'target_code_name',
                'class' => target::class,
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('hideouts', EntityType::class, [
                'choice_label' => 'hideout_code_name',
                'class' => hideout::class,
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('contacts', EntityType::class, [
                'choice_label' => 'contact_code_name',
                'class' => contact::class,
                'multiple' => true,
                'expanded' => true,
            ]);





        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Mission::class,
        ]);
    }
}

src/Controller/MissionsController.php
<?php

namespace App\Controller;

use App\Entity\Mission;
use App\Form\MissionType;
use App\Repository\MissionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
class MissionsController extends AbstractController
{
    #[Route('/', name: 'app_mission_index')]
    public function index(MissionRepository $missionRepository): Response
    {
        return $this->render('missions/index.html.twig', [
            'missions' => $missionRepository->findAll(),
        ]);
    }

    #[Route('admin/new', name: 'app_mission_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MissionRepository $missionRepository): Response
    {
        $mission = new Mission();
        $form = $this->createForm(MissionType::class, $mission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $missionRepository->add($mission, true);

            return $this->redirectToRoute('app_mission_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('missions/new.html.twig', [
            'mission' => $mission,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_mission_show', methods: ['GET'])]
    public function show(Mission $mission): Response
    {
        return $this->render('missions/show.html.twig', [
            'mission' => $mission,
        ]);
    }

    #[Route('admin/{id}/edit', name: 'app_mission_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Mission $mission, MissionRepository $missionRepository): Response
    {
        $form = $this->createForm(MissionType::class, $mission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $missionRepository->add($mission, true);

            return $this->redirectToRoute('app_mission_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('missions/edit.html.twig', [
            'mission' => $mission,
            'form' => $form,
        ]);
    }

    #[Route('admin/{id}', name: 'app_mission_delete', methods: ['POST'])]
    public function delete(Request $request, Mission $mission, MissionRepository $missionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $mission->getId(), $request->request->get('_token'))) {
            $missionRepository->remove($mission, true);
        }

        return $this->redirectToRoute('app_mission_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/missions/_delete_form.html.twig
{% if is_granted('ROLE_ADMIN') %}
    <form method="post" action="{{ path('app_mission_delete', {'id': mission.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mission.id) }}">
        <button class="btn">Delete</button>
    </form>
{% endif %}

templates/missions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Mission{% endblock %}

{% block body %}
    <h1>Edit Mission</h1>

    {{ include('missions/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_mission_index') }}">back to list</a>

    {{ include('missions/_delete_form.html.twig') }}
{% endblock %}

templates/missions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Missions index{% endblock %}

{% block body %}
    <h1>Missions index</h1>

    <table class="table table-responsive table-striped table-hover text-center">
        <thead>
            <tr>
                <th>Id</th>
                <th>Mission_code_name</th>
                <th>Title</th>
                <th>Description</th>
                <th>Mission_type</th>
                <th>Mission_status</th>
                <th>Start_date</th>
                <th>End_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for mission in missions %}
            <tr>
                <td>{{ mission.id }}</td>
                <td>{{ mission.missionCodeName }}</td>
                <td>{{ mission.title }}</td>
                <td>{{ mission.description }}</td>
                <td>{{ mission.missionType }}</td>
                <td>{{ mission.missionStatus }}</td>
                <td>{{ mission.startDate ? mission.startDate|date('Y-m-d') : '' }}</td>
                <td>{{ mission.endDate ? mission.endDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_mission_show', {'id': mission.id}) }}">show</a>
                    {% if is_granted('ROLE_ADMIN') %}
                    <a href="{{ path('app_mission_edit', {'id': mission.id}) }}">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('app_mission_new') }}">Create new mission</a>
    {% endif %}


{% endblock %}

templates/missions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Mission{% endblock %}

{% block body %}
    <h1>Create new Mission</h1>

    {{ include('missions/_form.html.twig') }}

    <a href="{{ path('app_mission_index') }}">back to list</a>
{% endblock %}

templates/missions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mission{% endblock %}

{% block body %}
    <h1>Mission</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mission.id }}</td>
            </tr>
            <tr>
                <th>Mission_code_name</th>
                <td>{{ mission.missionCodeName }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ mission.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ mission.description }}</td>
            </tr>
            <tr>
                <th>Mission_type</th>
                <td>{{ mission.missionType }}</td>
            </tr>
            <tr>
                <th>Mission_status</th>
                <td>{{ mission.missionStatus }}</td>
            </tr>
            <tr>
                <th>Start_date</th>
                <td>{{ mission.startDate ? mission.startDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ mission.endDate ? mission.endDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Target</th>
                <td>
                    {% for mission in mission.targets %}
                        <li>{{targets.target_code_name}}</li>
                    {% endfor %}
                </td>
            </tr>

            <tr>
        </tbody>
    </table>

    <a href="{{ path('app_mission_index') }}">back to list</a>

    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('app_mission_edit', {'id': mission.id}) }}">edit</a>
    {% endif %}




    {{ include('missions/_delete_form.html.twig') }}
{% endblock %}