src/Entity/Hideout.php
<?php

namespace App\Entity;

use App\Repository\HideoutRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HideoutRepository::class)]
class Hideout
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $hideout_code_name = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 50)]
    private ?string $country = null;

    #[ORM\Column(length: 255)]
    private ?string $hideout_type = null;

    #[ORM\ManyToOne(inversedBy: 'hideouts')]
    private ?Mission $mission = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHideoutCodeName(): ?string
    {
        return $this->hideout_code_name;
    }

    public function setHideoutCodeName(string $hideout_code_name): self
    {
        $this->hideout_code_name = $hideout_code_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getHideoutType(): ?string
    {
        return $this->hideout_type;
    }

    public function setHideoutType(string $hideout_type): self
    {
        $this->hideout_type = $hideout_type;

        return $this;
    }

    public function getMission(): ?Mission
    {
        return $this->mission;
    }

    public function setMission(?Mission $mission): self
    {
        $this->mission = $mission;

        return $this;
    }
}

src/Form/HideoutType.php
<?php

namespace App\Form;

use App\Entity\Hideout;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class HideoutType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('hideout_code_name')
            ->add('address')
            ->add('country', ChoiceType::class, [
                'choices' => [
                    'Belgium' => 'Belgium',
                    'Brazil' => 'Brazil',
                    'China' => 'China',
                    'Congo' => 'Congo',
                    'France' => 'France',
                    'Japan' => 'Japan',
                    'UK' => 'UK',
                    'USA' => 'USA',
                    'Russia' => 'Russia',
                    'Swiss' => 'Swiss',
                ]
            ])
            ->add('hideout_type', ChoiceType::class, [
                'choices' => [
                    'Observation' => 'Observation',
                    'Hotel' => 'Hotel',
                    'Flat' => 'Flat',
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Hideout::class,
        ]);
    }
}

src/Controller/HideoutController.php
<?php

namespace App\Controller;

use App\Entity\Hideout;
use App\Form\HideoutType;
use App\Repository\HideoutRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('admin/hideouts')]
class HideoutController extends AbstractController
{
    #[Route('/', name: 'app_hideout_index', methods: ['GET'])]
    public function index(HideoutRepository $hideoutRepository): Response
    {
        return $this->render('hideout/index.html.twig', [
            'hideouts' => $hideoutRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_hideout_new', methods: ['GET', 'POST'])]
    public function new(Request $request, HideoutRepository $hideoutRepository): Response
    {
        $hideout = new Hideout();
        $form = $this->createForm(HideoutType::class, $hideout);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hideoutRepository->add($hideout, true);

            return $this->redirectToRoute('app_hideout_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('hideout/new.html.twig', [
            'hideout' => $hideout,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_hideout_show', methods: ['GET'])]
    public function show(Hideout $hideout): Response
    {
        return $this->render('hideout/show.html.twig', [
            'hideout' => $hideout,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_hideout_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Hideout $hideout, HideoutRepository $hideoutRepository): Response
    {
        $form = $this->createForm(HideoutType::class, $hideout);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hideoutRepository->add($hideout, true);

            return $this->redirectToRoute('app_hideout_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('hideout/edit.html.twig', [
            'hideout' => $hideout,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_hideout_delete', methods: ['POST'])]
    public function delete(Request $request, Hideout $hideout, HideoutRepository $hideoutRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$hideout->getId(), $request->request->get('_token'))) {
            $hideoutRepository->remove($hideout, true);
        }

        return $this->redirectToRoute('app_hideout_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/hideout/_delete_form.html.twig
<form method="post" action="{{ path('app_hideout_delete', {'id': hideout.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ hideout.id) }}">
    <button class="btn">Delete</button>
</form>

templates/hideout/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Hideout{% endblock %}

{% block body %}
    <h1>Edit Hideout</h1>

    {{ include('hideout/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_hideout_index') }}">back to list</a>

    {{ include('hideout/_delete_form.html.twig') }}
{% endblock %}

templates/hideout/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hideout index{% endblock %}

{% block body %}
    <h1>Hideout index</h1>

    <table class="table table-responsive table-striped table-hover text-center">
        <thead>
            <tr>
                <th>Id</th>
                <th>Hideout_code_name</th>
                <th>Address</th>
                <th>Country</th>
                <th>Hideout_type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for hideout in hideouts %}
            <tr>
                <td>{{ hideout.id }}</td>
                <td>{{ hideout.hideoutCodeName }}</td>
                <td>{{ hideout.address }}</td>
                <td>{{ hideout.country }}</td>
                <td>{{ hideout.hideoutType }}</td>
                <td>
                    <a href="{{ path('app_hideout_show', {'id': hideout.id}) }}">show</a>
                    <a href="{{ path('app_hideout_edit', {'id': hideout.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_hideout_new') }}">Create new hideout</a>
{% endblock %}

templates/hideout/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Hideout{% endblock %}

{% block body %}
    <h1>Create new Hideout</h1>

    {{ include('hideout/_form.html.twig') }}

    <a href="{{ path('app_hideout_index') }}">back to list</a>
{% endblock %}

templates/hideout/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hideout{% endblock %}

{% block body %}
    <h1>Hideout</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ hideout.id }}</td>
            </tr>
            <tr>
                <th>Hideout_code_name</th>
                <td>{{ hideout.hideoutCodeName }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ hideout.address }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ hideout.country }}</td>
            </tr>
            <tr>
                <th>Hideout_type</th>
                <td>{{ hideout.hideoutType }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_hideout_index') }}">back to list</a>

    <a href="{{ path('app_hideout_edit', {'id': hideout.id}) }}">edit</a>

    {{ include('hideout/_delete_form.html.twig') }}
{% endblock %}